export const pokerGlossary: Record<string, string> = {
  "AKs": "Ace-King suited — both cards share the same suit (e.g., A♠K♠)",
  "AQs": "Ace-Queen suited — both cards share the same suit",
  "AJs": "Ace-Jack suited — both cards share the same suit",
  "ATs": "Ace-Ten suited — both cards share the same suit",
  "A9s": "Ace-Nine suited — both cards share the same suit",
  "KQs": "King-Queen suited — both cards share the same suit",
  "KJs": "King-Jack suited — both cards share the same suit",
  "QJs": "Queen-Jack suited — both cards share the same suit",
  "JTs": "Jack-Ten suited — both cards share the same suit",
  "T9s": "Ten-Nine suited — both cards share the same suit",
  "98s": "Nine-Eight suited — both cards share the same suit",
  "87s": "Eight-Seven suited — a suited connector with drawing potential",
  "76s": "Seven-Six suited — a suited connector with drawing potential",
  "65s": "Six-Five suited — a suited connector with drawing potential",
  "54s": "Five-Four suited — a suited connector with drawing potential",
  "AKo": "Ace-King offsuit — the two cards are different suits (e.g., A♠K♥)",
  "AQo": "Ace-Queen offsuit — the two cards are different suits",
  "AJo": "Ace-Jack offsuit — the two cards are different suits",
  "KQo": "King-Queen offsuit — the two cards are different suits",
  "QJo": "Queen-Jack offsuit — the two cards are different suits",
  "72o": "Seven-Two offsuit — widely considered the worst starting hand in poker",
  "AA": "Pocket Aces — the strongest starting hand in Texas Hold'em",
  "KK": "Pocket Kings — the second-strongest starting hand",
  "QQ": "Pocket Queens — the third-strongest starting hand",
  "JJ": "Pocket Jacks — a strong but tricky starting hand",
  "TT": "Pocket Tens — a strong pair, but vulnerable to overcards",
  "AK": "Ace-King — \"Big Slick,\" a premium drawing hand",
  "AQ": "Ace-Queen — a strong hand, especially suited",
  "AJ": "Ace-Jack — a decent hand, better when suited",
  "KQ": "King-Queen — a strong broadway hand",
  "22": "Pocket Twos — the smallest pocket pair, best played for set mining",
  "UTG": "Under the Gun — first player to act preflop, the earliest and most disadvantaged position",
  "UTG+1": "Under the Gun plus one — second player to act preflop, still early position",
  "MP": "Middle Position — acts after early position players, moderate information advantage",
  "MP+1": "Middle Position plus one — fourth to act preflop",
  "HJ": "Hijack — two seats before the dealer button, a late-middle position",
  "CO": "Cutoff — one seat before the dealer button, a strong late position",
  "BTN": "Button — the dealer position, last to act post-flop with maximum information advantage",
  "SB": "Small Blind — posts half the minimum bet, first to act post-flop",
  "BB": "Big Blind — posts the full minimum bet, last to act preflop",
  "EV": "Expected Value — the average long-term result of a decision, positive (+EV) means profitable",
  "GTO": "Game Theory Optimal — a mathematically balanced strategy that cannot be exploited",
  "TAG": "Tight-Aggressive — a playing style using selective hand choices with aggressive betting",
  "LAG": "Loose-Aggressive — a playing style playing many hands with frequent aggression",
  "C-Bet": "Continuation Bet — a bet on the flop by the preflop raiser, regardless of whether they hit",
  "3-bet": "Three-bet — a re-raise of an initial raise preflop",
  "3-betting": "Three-betting — re-raising an initial raiser preflop to build the pot or apply pressure",
  "all-in": "All-in — betting all of your remaining chips on a single hand",
  "equity": "Equity — your percentage chance of winning the hand based on current cards and possible outcomes",
  "pot odds": "Pot Odds — the ratio between the current pot size and the cost of your call",
  "implied odds": "Implied Odds — expected future winnings factored into the current call decision",
  "outs": "Outs — cards remaining in the deck that can improve your hand to a likely winner",
  "hole cards": "Hole Cards — the two private cards dealt face-down to each player",
  "community cards": "Community Cards — the five shared cards dealt face-up on the board (flop, turn, river)",
  "flop": "Flop — the first three community cards dealt face-up on the board",
  "turn": "Turn — the fourth community card, also called \"fourth street\"",
  "river": "River — the fifth and final community card, also called \"fifth street\"",
  "showdown": "Showdown — when remaining players reveal their cards to determine the winner",
  "preflop": "Preflop — the first betting round before any community cards are dealt",
  "pre-flop": "Pre-flop — the first betting round before any community cards are dealt",
  "post-flop": "Post-flop — any betting round after the flop has been dealt",
  "kicker": "Kicker — an unpaired card used to break ties between hands of the same rank",
  "suited": "Suited — when both hole cards share the same suit, increasing flush potential",
  "offsuit": "Offsuit — when hole cards are different suits, reducing flush potential",
  "broadway": "Broadway — any card Ten or higher (T, J, Q, K, A); a broadway straight is A-K-Q-J-T",
  "broadway cards": "Broadway Cards — cards ranked Ten or higher (T, J, Q, K, A)",
  "suited connectors": "Suited Connectors — two consecutive cards of the same suit (e.g., 8♠7♠), good for making straights and flushes",
  "set mining": "Set Mining — calling preflop with a small pair hoping to hit three of a kind on the flop",
  "flush draw": "Flush Draw — having four cards of the same suit, needing one more for a flush",
  "straight draw": "Straight Draw — having four consecutive cards, needing one more for a straight",
  "open-ended straight draw": "Open-Ended Straight Draw — four consecutive cards that can complete a straight with a card on either end (8 outs)",
  "semi-bluff": "Semi-Bluff — betting with a hand that's currently weak but has potential to improve (e.g., a flush draw)",
  "semi-bluffs": "Semi-Bluffs — bets made with hands that are currently weak but have potential to improve",
  "continuation bet": "Continuation Bet — a bet on the flop by the preflop raiser, maintaining the initiative",
  "continuation betting": "Continuation Betting — betting the flop after raising preflop, regardless of hitting the board",
  "value bet": "Value Bet — a bet made with a strong hand to get called by a weaker hand",
  "value betting": "Value Betting — betting for value with strong hands to maximize winnings",
  "check-raise": "Check-Raise — checking initially then raising after an opponent bets, often used as a trap or bluff",
  "blind stealing": "Blind Stealing — raising from late position to try to win the blinds uncontested",
  "tilt": "Tilt — playing emotionally rather than rationally, usually after bad beats or frustration",
  "bad beat": "Bad Beat — losing a hand where you were a strong statistical favorite",
  "bad beats": "Bad Beats — losing hands where you were a strong statistical favorite",
  "cooler": "Cooler — a situation where two very strong hands clash and the loser couldn't avoid losing chips",
  "coolers": "Coolers — situations where two very strong hands clash unavoidably",
  "bankroll": "Bankroll — the total amount of money a player has set aside specifically for playing poker",
  "variance": "Variance — the natural ups and downs in poker results due to the randomness of card distribution",
  "muck": "Muck — to discard your hand without showing it",
  "fold equity": "Fold Equity — the probability that your opponent will fold when you bet or raise",
  "board texture": "Board Texture — the pattern and relationships among community cards (e.g., suited, connected, paired)",
  "range": "Range — the set of all possible hands a player could have in a given situation",
  "table image": "Table Image — how other players perceive your playing style based on your recent actions",
  "calling station": "Calling Station — a player who calls too often and rarely folds or raises",
  "stack": "Stack — the total number of chips a player has at the table",
  "buy-in": "Buy-in — the amount of money required to join a poker game or tournament",
  "buy-ins": "Buy-ins — the amounts required to enter poker games, used to measure bankroll (e.g., 20-30 buy-ins)",
  "blinds": "Blinds — forced bets posted by two players before cards are dealt to create initial action",
  "bubble": "Bubble — the point in a tournament just before reaching paid positions",
  "overcards": "Overcards — hole cards higher in rank than any card on the board",
  "tight": "Tight — a selective playing style where a player folds most hands and only plays strong holdings",
  "coordinated flop": "Coordinated Flop — a flop where the cards connect well together (e.g., 8-9-10), creating many possible straights, flushes, or draws",
  "laydown": "Laydown — folding a strong hand because you believe your opponent has something better; a 'tough laydown' is especially hard to make",
  "connectors": "Connectors — two hole cards consecutive in rank (e.g., 8-9 or J-Q); suited connectors share the same suit for added flush potential",
  "stealing blinds": "Stealing Blinds — raising from late position to win the small and big blind without seeing a flop",
  "open-ended": "Open-Ended — a straight draw with four consecutive cards where a card on either end completes it (8 outs)",
  "gutshot": "Gutshot — an inside straight draw needing one specific middle card to complete (only 4 outs), e.g., holding 5-6-8-9 and needing a 7",
};
